# Generated by Django 6.0.2 on 2026-02-25 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20201024_2335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='filmgenre',
            options={'ordering': ['name'], 'verbose_name': 'Género de película', 'verbose_name_plural': 'Géneros de película'},
        ),
        migrations.AlterField(
            model_name='film',
            name='review_large',
            field=models.TextField(blank=True, null=True, verbose_name='Reseña larga'),
        ),
        migrations.AlterField(
            model_name='film',
            name='review_short',
            field=models.TextField(blank=True, null=True, verbose_name='Reseña corta'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='URL del trailer'),
        ),
        migrations.AlterField(
            model_name='filmgenre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filmgenre',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del género'),
        ),
        migrations.CreateModel(
            name='FilmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Sin estado'), (1, 'Vista'), (2, 'Quiero ver')], default=0, verbose_name='Estado')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorita')),
                ('note', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Reseña personal')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Película')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['film__title'],
                'unique_together': {('user', 'film')},
            },
        ),
    ]
