# Generated by Django 6.0.2 on 2026-02-25 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_options_alter_filmgenre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='average_note',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='nota media'),
        ),
        migrations.AddField(
            model_name='film',
            name='favorites',
            field=models.IntegerField(default=0, verbose_name='favoritos'),
        ),
    ]
